FROM registry.access.redhat.com/ubi8

#------------------------------------------------------------------------------
# Variables
#------------------------------------------------------------------------------
ENV PLUGIN_REPO="https://releases.hashicorp.com" \
TERRAFORM_VERSION=1.0.4 \
TERRAGRUNT_VERSION=0.31.1 \
ARCHIVE_VERSION=2.2.0 \
AWS_VERSION=3.51.0 \
NULL_VERSION=3.1.0 \
TEMPLATE_VERSION=2.2.0 \
TFLINT_VERSION=v0.30.0 \
TFSEC_VERSION=v0.52.1

#------------------------------------------------------------------------------
# Software Pre Reqs
#------------------------------------------------------------------------------

RUN yum update -y && \
yum install -y unzip wget curl openssl git

#------------------------------------------------------------------------------
# AWSCLI
#------------------------------------------------------------------------------

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
unzip awscliv2.zip && \
./aws/install && \
rm -rf awscliv2.zip

#------------------------------------------------------------------------------
# Terraform
#------------------------------------------------------------------------------

RUN wget -qP /tmp "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" && \
unzip /tmp/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin/ && \
chmod +rx /usr/local/bin/terraform*

ADD ${PLUGIN_REPO}/terraform-provider-archive/${ARCHIVE_VERSION}/terraform-provider-archive_${ARCHIVE_VERSION}_linux_amd64.zip ./
ADD ${PLUGIN_REPO}/terraform-provider-aws/${AWS_VERSION}/terraform-provider-aws_${AWS_VERSION}_linux_amd64.zip ./
ADD ${PLUGIN_REPO}/terraform-provider-null/${NULL_VERSION}/terraform-provider-null_${NULL_VERSION}_linux_amd64.zip ./
ADD ${PLUGIN_REPO}/terraform-provider-template/${TEMPLATE_VERSION}/terraform-provider-template_${TEMPLATE_VERSION}_linux_amd64.zip ./

RUN for i in $(ls *.zip); do unzip -od /usr/local/bin/ ${i} terraform-provider\*; done \
&& rm *.zip \
&& chmod +rx /usr/local/bin/terraform-provider-*

#------------------------------------------------------------------------------
# Terragrunt
#------------------------------------------------------------------------------

RUN wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 && \
mv terragrunt_linux_amd64 /usr/local/bin/terragrunt && \
chmod u+x /usr/local/bin/terragrunt

#------------------------------------------------------------------------------
# tflint
#------------------------------------------------------------------------------

RUN curl -L https://github.com/wata727/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip > tflin_${TFLINT_VERSION}_linux_amd64.zip && \
unzip tflin_${TFLINT_VERSION}_linux_amd64.zip -d /usr/local/bin && \
rm -f tflin_${TFLINT_VERSION}_linux_amd64.zip

#------------------------------------------------------------------------------
# tfsec
#------------------------------------------------------------------------------

RUN curl -L https://github.com/tfsec/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64 \
-o /bin/tfsec && chmod +x /bin/tfsec

#------------------------------------------------------------------------------
# Version Checks
#------------------------------------------------------------------------------

RUN terraform -version \
&& terragrunt -version \
&& tflint --version \
&& tfsec -version \
&& aws --version