version: 0.2

phases:
  install:
    commands:
      - echo ***TERRAFORM INIT***
      - terraform init
  build:
    commands:
      - echo ***TERRAFORM APPLY***
      - terraform apply --auto-approve