version: 0.2

phases:
  pre_build:
    commands:
      - terraform -version
      - terragrunt -version
      - tflint --version
      - tfsec -version
      - aws --version
  install:
    commands:
      - echo ***TERRAFORM INIT***
      - ./pipelines/execute.sh "terraform init"
  build:
    commands:
      - echo ***CODE SECURITY ANALYSIS***
      - ./pipelines/execute.sh "tfsec"